using Xamarin.Forms;

namespace GuitarLearning_Mobile
{
    /// <summary>
    /// Generic apllication class, generated by VisualStudio.
    /// </summary>
    public partial class App : Application
    {
        /// <summary>
        /// Constructor
        /// <para>Code which changes the colour of the navigation-bar has been added.</para>
        /// </summary>
        public App()
        {
            InitializeComponent();

            var navigationPage = new NavigationPage(new MainPage());
            navigationPage.BarBackgroundColor = Color.LimeGreen;
            navigationPage.BarTextColor = Color.White;
            MainPage = navigationPage;
        }

        /// <summary>
        /// Not used
        /// </summary>
        protected override void OnStart()
        {
        }

        /// <summary>
        /// Not used
        /// </summary>
        protected override void OnSleep()
        {
        }

        /// <summary>
        /// Not used
        /// </summary>
        protected override void OnResume()
        {
        }
    }
}
